[build-system]
requires = ["setuptools>=44", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
dependencies = ["numpy~=2.2.2", "scipy~=1.15.1"]
requires-python = ">=3.11"
